server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

langchain4j:
  google-ai-gemini:
    streaming-chat-model:
      api-key: ${GEMINI_API_KEY}
      model-name: ${GEMINI_MODEL}
      log-requests-and-responses: false
    chat-model:
      api-key: ${GEMINI_API_KEY}
      model-name: ${GEMINI_MODEL}
      log-requests-and-responses: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false